spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: chat-producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nytins.kafka.HelloSerializer
    consumer:
      group-id: chat-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.nytins.kafka.HelloDeserializer
